name: codecov

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: [ 3.7, 3.8 ]

    steps:
    - name: Codecov-coverage
      uses: codecov/codecov-action@v3